# Generated by Django 5.2.4 on 2025-07-25 00:37

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(max_length=50)),
                ("nome", models.CharField(max_length=100)),
                ("nivel", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("ponto", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Complexidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(choices=[("1", "C1"), ("2", "C2"), ("3", "C3")]),
                ),
                ("ponto", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Criticidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("1", "baixa"),
                            ("2", "normal"),
                            ("3", "grave"),
                            ("4", "critica"),
                        ]
                    ),
                ),
                ("ponto", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("1", "SLA"),
                            ("2", "Desenvolvimento Interno"),
                            ("3", "Projetos Estruturantes"),
                        ]
                    ),
                ),
                ("ponto", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tempo_estimado", models.FloatField()),
                ("tempo_gasto", models.FloatField()),
                (
                    "dt_inclusao",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 7, 25, 0, 37, 21, 912982, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("dt_entrega", models.DateTimeField(blank=True, null=True)),
                ("dt_encerramento", models.DateTimeField(blank=True, null=True)),
                (
                    "idclasse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="games.classe"
                    ),
                ),
                (
                    "idcomplexidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="games.complexidade",
                    ),
                ),
                (
                    "idcriticidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="games.criticidade",
                    ),
                ),
                (
                    "idservico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="games.servico"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Historico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt_inclusao", models.DateTimeField(auto_now_add=True)),
                ("finalizada", models.BooleanField()),
                ("pontos", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "idtarefa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="games.tarefa"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "idade",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(16),
                            django.core.validators.MaxValueValidator(60),
                        ]
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminio"), ("O", "Outros")],
                        max_length=1,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("senha", models.CharField(max_length=100)),
                (
                    "idcargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="games.cargo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recompensa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("foto", models.URLField()),
                ("descricao", models.TextField()),
                ("total_pontos", models.IntegerField()),
                ("dt_inclusao", models.DateTimeField(auto_now_add=True)),
                (
                    "idhistorico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="games.historico",
                    ),
                ),
                (
                    "idusuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="games.usuario"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="historico",
            name="idusuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="games.usuario"
            ),
        ),
    ]
