# Generated by Django 5.2.4 on 2025-07-25 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="dt_inclusao",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 25, 0, 44, 22, 327371, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
