# Generated by Django 5.2.4 on 2025-07-29 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_alter_tarefa_dt_inclusao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarefa",
            name="idclasse",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="idade",
        ),
        migrations.AddField(
            model_name="tarefa",
            name="classe",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="dt_inclusao",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 29, 22, 14, 20, 430738, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="genero",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outros")],
                max_length=1,
            ),
        ),
        migrations.DeleteModel(
            name="Classe",
        ),
    ]
