# Generated by Django 5.2.4 on 2025-07-29 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_remove_tarefa_idclasse_remove_usuario_idade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="dt_inclusao",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 29, 22, 14, 49, 308329, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
